# Generated by Django 4.1.2 on 2022-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserIpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('times_user_viewed', models.IntegerField(default=0)),
            ],
        ),
    ]
