# Generated by Django 4.1.2 on 2022-10-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useripaddress',
            name='user_ip_without_proxy',
            field=models.CharField(default=11, max_length=100),
            preserve_default=False,
        ),
    ]
