# Generated by Django 4.1.2 on 2022-11-26 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_useripaddress_user_ip_without_proxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useripaddress',
            name='date',
        ),
        migrations.AddField(
            model_name='useripaddress',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
