# Generated by Django 4.1.2 on 2022-11-27 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_useripaddress_date_useripaddress_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('user_ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.useripaddress')),
            ],
        ),
    ]
